### ISSUE TITLE
Verify existance of item and return 404 if false

### ISSUE THREAD

**Issue by ztickm** [ztickm/reja3li_backend#3]
## Expected behavior:
Querying items that don't exist in the collection should return a 404 status code
## Current behavior:
Querying items that don't exist returns a 200 status code
## How to reproduce:
Using an http client, query (get / put / delete) an item through `{server}:{port}/items/{item _id}`

**Comment by yaacine** [comment]
issue resolved here ==> https://github.com/ztickm/reja3li_backend/pull/4/
